# Generated by Django 4.0.3 on 2022-05-25 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_list_closed_auction_list_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL)),
                ('win_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win_item', to='auctions.auction_list')),
            ],
        ),
    ]
