# Generated by Django 4.0.3 on 2022-05-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_list_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='image',
            field=models.CharField(default='test', max_length=64),
        ),
    ]
