# Generated by Django 4.0.3 on 2022-05-25 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_list',
            name='comment',
        ),
        migrations.CreateModel(
            name='cmt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(default='', max_length=500)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='criticism', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auction_list',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='some_words', to='auctions.cmt'),
        ),
    ]
