# Generated by Django 4.0.3 on 2022-05-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_list_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='current_bid',
            field=models.IntegerField(default=''),
        ),
    ]
