# Generated by Django 4.0.3 on 2022-05-25 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_auction_list_comment_cmt_auction_list_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmt',
            name='post_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
