# Generated by Django 4.0.3 on 2022-05-12 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_list_desc_alter_auction_list_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='watch_user',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
