# Generated by Django 4.0.3 on 2022-05-15 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_list_desc_alter_auction_list_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='watch_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_watching', models.BooleanField(default=False)),
                ('all_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
