# Generated by Django 4.0.3 on 2022-05-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watch_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch_list',
            name='is_watching',
        ),
        migrations.RemoveField(
            model_name='watch_list',
            name='all_list',
        ),
        migrations.AddField(
            model_name='watch_list',
            name='all_list',
            field=models.ManyToManyField(blank=True, related_name='watch_lists', to='auctions.auction_list'),
        ),
    ]
