# Generated by Django 4.0.3 on 2022-05-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_watch_list_is_watching_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch_list',
            name='all_list',
            field=models.ManyToManyField(blank=True, related_name='now_watch', to='auctions.auction_list'),
        ),
    ]
